networks:
  my_minecraft_network:
    external: False

services:
  minecraft_discord_bot:
    image: minecraft_discord_bot
    container_name: minecraft_discord_bot
    build:
      context: .
      dockerfile: Dockerfile.yaml
    restart: unless-stopped
    environment:
      MINECRAFT_HOSTNAME: minecraft_server
      MEMCACHED_HOSTNAME: minecraft_discord_memcached
      MEMCACHED_PORT: 11211
      MEMCACHED_USERNAME: my_user
      MEMCACHED_PASSWORD: my_password

      DISCORD_TOKEN: "9a98sud89as7u89da7u8s9c98uv9as8du89as89da89s9ucau98s"
      DISCORD_PREFIX: "mc."
      DISCORD_DESCRIPTION: "Welcome welcome, I'm a bot"
      DISCORD_MC_URL: "url.domain.com:port"

    depends_on:
      - minecraft_discord_memcached

  minecraft_discord_memcached:
    image: bitnami/memcached:latest
    container_name: minecraft_discord_memcached
    environment:
      MEMCACHED_USERNAME: my_user
      MEMCACHED_PASSWORD: my_password
      MEMCACHED_THREADS: 4
      MEMCACHED_MAX_ITEM_SIZE: 8388608
    links:
      - minecraft_discord_bot


  minecraft_server:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    networks:
      my_minecraft_network:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data:rw
    user: "1234:1234"
    ports:
      - 25565:25565
    environment:
      MEMORY: 3G
      TYPE: SPIGOT
      FORCE_REDOWNLOAD: "TRUE"
      EULA: "TRUE"
      VERSION: "1.17.1"
      SERVER_NAME: "Very cool minecraft world"
      MOTD: "§a.This§b is §ca§d Minecraft §eWorld"
      ONLINE_MODE: False
      ENABLE_AUTOPAUSE: True
      MAX_TICK_TIME: -1
      ENABLE_QUERY: True
      #      ENABLE_AUTOPAUSE: "true"
      #      ENABLE_RCON: "true"
      #      RCON_PASSWORD: ${RCON_PASSWORD}
      #      RCON_PORT: 28016
      #      JVM_OPTS:
    restart: unless-stopped