networks:
  my_minecraft_network:
    external: False

services:
  minecraft_discord_bot:
    image: minecraft_discord_bot
    container_name: minecraft_discord_bot
    build:
      context: .
      dockerfile: Dockerfiles/Bot.yaml
    restart: unless-stopped
    environment:
      MINECRAFT_HOSTNAME: minecraft_server
      MEMCACHED_HOSTNAME: minecraft_discord_memcached
      MEMCACHED_PORT: 11211
      MEMCACHED_USERNAME: my_user
      MEMCACHED_PASSWORD: my_password

      DISCORD_TOKEN: "my_token"
      DISCORD_PREFIX: "mc."
      DISCORD_DESCRIPTION: "Welcome welcome, I'm a bot"
      DISCORD_MC_URL: "url.domain.com:port"

    networks:
      my_minecraft_network:

  minecraft_discord_memcached:
    image: bitnami/memcached:latest
    container_name: minecraft_discord_memcached
    environment:
      MEMCACHED_USERNAME: my_user
      MEMCACHED_PASSWORD: my_password
      MEMCACHED_THREADS: 4
      MEMCACHED_MAX_ITEM_SIZE: 8388608
    restart: unless-stopped
    networks:
      my_minecraft_network:

  minecraft_server:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    networks:
      my_minecraft_network:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data:rw
    user: "1000:1000"
    ports:
          - "25565:25565/tcp"
    environment:
      EULA: "TRUE"
      MEMORY: 2G
      TYPE: SPIGOT
      FORCE_REDOWNLOAD: "TRUE"
      VERSION: "1.18.2"
      MOTD: "My minecraft world!"
      ONLINE_MODE: "FALSE"
      ENABLE_QUERY: "TRUE"
      ENABLE_RCON: "FALSE"
    restart: unless-stopped
